## Python programming and Data Analysis

## [Sample solution] Class Exercise 4

In [1]:
import numpy as np
import pandas as pd

## Numpy

### Exercise 4.11

In [ ]:
arr_1 = np.arange(10,-11,-1)
arr_2 = np.zeros((10,))
arr_3 = np.ones((15,))
arr_4 = np.arange(5,14).reshape(3,3)
arr_5 = np.random.rand(3, 3)
arr_6 = np.arange(1,10).reshape(3,3).T
arr_7 = np.arange(1,10).reshape(3,3)[:,::-1]
arr_8 = np.arange(1,10).reshape(3,3)[::-1,::-1]

Create the following numpy arrays:

**1**. a vector containing number 10 to -10 in descending order.

In [2]:
arr_1 = np.arange(10,-11,-1)
print(arr_1)

[ 10   9   8   7   6   5   4   3   2   1   0  -1  -2  -3  -4  -5  -6  -7
  -8  -9 -10]


**2**. a vector containing 10 zeros.

In [3]:
arr_2 = np.zeros((10,))
print(arr_2)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


**3**. a vector containing 15 ones.

In [4]:
arr_3 = np.ones((15,))
print(arr_3)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


**4**. this 3x3 matrix:
```
5 6 7
8 9 10
11 12 13
```

In [5]:
arr_4 = np.arange(5,14).reshape(3,3)
print(arr_4)

[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]]


**5**. a 3x3 matrix with random numbers

In [6]:
arr_5 = np.random.rand(3, 3)
print(arr_5)

[[0.43008466 0.35717116 0.39590249]
 [0.96655984 0.61327482 0.62390726]
 [0.63801693 0.51829928 0.79468279]]


**6**. this 3x3 matrix (without typing every element):
```
1 4 7
2 5 8
3 6 9
```

In [7]:
arr_6 = np.arange(1,10).reshape(3,3).T
print(arr_6)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


**7**. this 3x3 matrix (without typing every element):
```
3 2 1
6 5 4
9 8 7
```

In [8]:
arr_7 = np.arange(1,10).reshape(3,3)[:,::-1]
# can also use np.array([[i+j*3 for i in range(3,0,-1)] for j in range(3)])
print(arr_7)

[[3 2 1]
 [6 5 4]
 [9 8 7]]


**8**. this 3x3 matrix (without typing every element):
```
9 8 7
6 5 4
3 2 1
```

In [9]:
arr_8 = np.arange(1,10).reshape(3,3)[::-1,::-1]  # or np.arange(9,0,-1).reshape(3,3)
print(arr_8)

[[9 8 7]
 [6 5 4]
 [3 2 1]]


### Exercise 4.12

Define a function ```to_nested_list()``` that takes a 2d array and returns the corresponding nested list.

For example:
```python
print(to_nested_list(np.array([[1, 2, 3], [4, 5, 6]]))
```

will output
```python
[[1, 2, 3],  [4, 5, 6]]
```

In [10]:
# test case
arr_test = np.arange(1,7).reshape(2,3)
arr_test

array([[1, 2, 3],
       [4, 5, 6]])

In [11]:
def to_nested_list(arr):
    return [list(row) for row in arr]   # can also use arr.tolist()

In [12]:
to_nested_list(arr_test)

[[1, 2, 3], [4, 5, 6]]

## Pandas

### Exercise 4.13

**1**. Given two lists of the same size, `l1` and `l2`, use `l1` as the index and `l2` as the data to create a pandas Series `s`.

In [13]:
l1 = list(range(5, 20, 2))
print(l1)
l2 = [5*n for n in range(len(l1))]
print(l2)

[5, 7, 9, 11, 13, 15, 17, 19]
[0, 5, 10, 15, 20, 25, 30, 35]


In [14]:
s = pd.Series(l2, index=l1)
print(s)

5      0
7      5
9     10
11    15
13    20
15    25
17    30
19    35
dtype: int64


**2**. create another pandas Series `s1` from `s`, using the index in `s` as data in `s1` and the data in `s` as index in `s1`.

In [15]:
s1 = pd.Series(s.index, index=s.values)
print(s1)

0      5
5      7
10     9
15    11
20    13
25    15
30    17
35    19
dtype: int64


**3**. multiply all items in `s` by 2.

In [16]:
s = s*2
print(s)

5      0
7     10
9     20
11    30
13    40
15    50
17    60
19    70
dtype: int64


**4**. change the index of `s` to lower-case letters 'a', 'b', ..., 'h'.

In [17]:
s.index = ['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h']   # or simply list('abcdefgh')
print(s)

a     0
b    10
c    20
d    30
e    40
f    50
g    60
h    70
dtype: int64


**5**. define a function to add 1 to first item in `s`, 2 to second item, 3 to third item, etc.

In [18]:
s

a     0
b    10
c    20
d    30
e    40
f    50
g    60
h    70
dtype: int64

In [19]:
def add_n(ser):
    # ser = ser + [i+1 for i in range(len(ser))]  # method 4
    for i in range(len(ser)):
        ser[ser.index[i]] += i+1   # method 1
        # ser.iloc[i] += i+1   # method 2
    return ser

add_n(s)

a     1
b    12
c    23
d    34
e    45
f    56
g    67
h    78
dtype: int64

### Exercise 4.14

1. Given a dictionary containing student names and their marks of three courses, create a DataFrame with their names as index and course names as columns.
```python
marks = { 'Names': ['James', 'Andrew', 'Bob', 'Carlson'],
          'English': [58, 62, 77, 65],
          'Chinese': [55, 32, 64, 80],
          'Math': [61, 70, 81, 54]}
```

In [20]:
marks = { 
    'Names': ['James', 'Andrew', 'Bob', 'Carlson'],
    'English': [58, 62, 77, 65],
    'Chinese': [55, 32, 64, 80],
    'Math': [61, 70, 81, 54]
}

df = pd.DataFrame(marks)
df.set_index('Names', inplace=True)
print(df)

         English  Chinese  Math
Names                          
James         58       55    61
Andrew        62       32    70
Bob           77       64    81
Carlson       65       80    54


2. Given a dictionary containing students names and their marks of three courses, create a DataFrame with their names as index and course names as columns. Use the same column names as above.
```
marks = {'James': [58, 55, 61],
         'Andrew': [62, 32, 70],
         'Bob': [77, 64, 81],
         'Carlson': [65, 80, 54]}
```

In [21]:
marks = {
    'James': [58, 55, 61],
    'Andrew': [62, 32, 70],
    'Bob': [77, 64, 81],
    'Carlson': [65, 80, 54]
}

df = pd.DataFrame(marks.values(),
                  index=marks.keys(),
                  columns=['English', 'Chinese', 'Math'])
print(df)

         English  Chinese  Math
James         58       55    61
Andrew        62       32    70
Bob           77       64    81
Carlson       65       80    54
