## Python programming and Data Analysis

## Class Exercise 4

## Numpy

#### Motivation For Numpy

In [1]:
def add_list(size_of_list):
    l1 = list(range(size_of_list))
    l2 = list(range(size_of_list))
    l = [l1[i] + l2[i] for i in range(size_of_list)]
    return l

In [2]:
size = 10000000

In [3]:
%%time
add_list(size)[0:10]

Wall time: 1.57 s


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]

In [4]:
import numpy as np

In [5]:
def add_ndarray(size_of_array):
    l1 = np.arange(size_of_array)
    l2 = np.arange(size_of_array)
    return l1 + l2

In [6]:
%%time
add_ndarray(size)[:10]

Wall time: 44.3 ms


array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

####  NumPy ndarrays

In [7]:
import numpy as np

In [8]:
arr = np.array([0, 1, 1, 2, 3, 5])
print(arr)

[0 1 1 2 3 5]


In [9]:
arr2d = np.array([ [0, 1, 1], 
                   [2, 3, 5] ])
print(arr2d)

[[0 1 1]
 [2 3 5]]


In [10]:
print(arr.ndim)
print(arr.shape)

1
(6,)


In [11]:
print(arr2d.ndim)
print(arr2d.shape)

2
(2, 3)


In [12]:
# creating an ndarray with all zero

arr0s = np.zeros((3, 3))
print(arr0s)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [13]:
# creating an ndarray with all one

arr1s = np.ones((3, 3))
print(arr1s)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
# arange() method

arr_seq = np.arange(15)
print(arr_seq)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]


In [15]:
# random.randn()
arr_rnd = np.random.randn(3, 4)
print(arr_rnd)

[[-0.47314078 -0.97208328 -0.41614976  0.86444102]
 [ 0.90917415  0.5306727   0.18415595  2.38336212]
 [-1.08358458 -0.19554011 -0.43745605 -2.37908373]]


In [16]:
# eye

arr_eye = np.eye(3)
print(arr_eye)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
np.random.rand(3, 3)

array([[0.61549826, 0.06904412, 0.43601795],
       [0.9180244 , 0.66795991, 0.14742491],
       [0.90224422, 0.69874312, 0.0924102 ]])

In [18]:
# indexing and slicing
# 1d array

arr1d = np.array([2, 3, 4, 5, 6, 7, 9])

print(arr1d)
print(arr1d[2])
print(arr1d[2:5])
print(arr1d[:-1:2])

[2 3 4 5 6 7 9]
4
[4 5 6]
[2 4 6]


In [19]:
# indexing and slicing
# 2d array

arr2d = np.array(
        [[i+j*4 for i in range(4)] 
          for j in range(4)])
print(arr2d)
print(arr2d[0, 2])
print(arr2d[0, :])
print(arr2d[0:3, 1:2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
2
[0 1 2 3]
[[1]
 [5]
 [9]]


In [20]:
# Boolean Masking

arr = np.arange(5)
arr_bl = arr > 2
print(arr_bl)

[False False False  True  True]


In [21]:
# random user data in 4x2 matrix
arr_dat = np.random.rand(4, 2)
print(arr_dat)

# user id from 0 to 3
arr_id = np.arange(4)
print(arr_id)

# pick data for user id 2
print(arr_dat[arr_id == 2])

# pick data for user id 0 and 3
print(arr_dat[ (arr_id == 0) 
              | (arr_id == 3) ])

[[0.76266571 0.67570843]
 [0.01224783 0.77907534]
 [0.90068058 0.13939494]
 [0.85391065 0.19988098]]
[0 1 2 3]
[[0.90068058 0.13939494]]
[[0.76266571 0.67570843]
 [0.85391065 0.19988098]]


In [22]:
# Math and Stat Functions

arr = np.arange(16)
print(arr.sum())
print(arr.mean(), arr.std())
print(arr.min(), arr.max())

120
7.5 4.6097722286464435
0 15


In [23]:
print(arr.cumsum())
print(arr.cumprod())

[  0   1   3   6  10  15  21  28  36  45  55  66  78  91 105 120]
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


#### Vector and Matrix Computation with NumPY

In [24]:
# Vector arithmetic
arr1 = np.arange(5)
arr2 = np.array(range(5, 0, -1))
print(arr1 + arr2)
print(arr1 - arr2)
print(arr1 * arr2)
print(arr1 / arr2)


[5 5 5 5 5]
[-5 -3 -1  1  3]
[0 4 6 6 4]
[0.         0.25       0.66666667 1.5        4.        ]


In [25]:
print(arr1 + 1)
print(arr1 * 2)
print(1 / arr2)

[1 2 3 4 5]
[0 2 4 6 8]
[0.2        0.25       0.33333333 0.5        1.        ]


In [26]:
print(arr1 > arr2)

[False False False  True  True]


In [27]:
# Matrix Manipulation & Computation

arr1 = np.arange(9)
print(arr1, arr1.shape)
mat1 = arr1.reshape(3, 3)
print(mat1, mat1.shape)

[0 1 2 3 4 5 6 7 8] (9,)
[[0 1 2]
 [3 4 5]
 [6 7 8]] (3, 3)


In [28]:
mat2 = arr1.reshape(3, -1)
print(mat2, mat2.shape)

[[0 1 2]
 [3 4 5]
 [6 7 8]] (3, 3)


In [29]:
#mat2 = arr1.reshape(4, -1)   # ValueError: cannot reshape array of size 9 into shape (4,newaxis)

In [30]:
# Linear Algebra

# transpose
m = np.arange(6).reshape(2, 3)
print(m, '\n', m.T)

[[0 1 2]
 [3 4 5]] 
 [[0 3]
 [1 4]
 [2 5]]


In [31]:
# dot product and matrix multiplication

m1 = np.arange(12).reshape(3, 4)
m2 = np.arange(8).reshape(4, 2) + 1
print(m1, '\n', m2)
print(np.dot(m1, m2))
print(m1.dot(m2))
print(m1 @ m2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[ 34  40]
 [ 98 120]
 [162 200]]
[[ 34  40]
 [ 98 120]
 [162 200]]
[[ 34  40]
 [ 98 120]
 [162 200]]


In [32]:
# useful linear algebra functions
m = np.arange(16).reshape(4, -1) + 1
print(np.diag(m))
print(np.trace(m))
print(np.linalg.det(m))

[ 1  6 11 16]
34
-1.820448242817726e-31


# Pandas

In [36]:
import pandas as pd

#### Pandas Series

In [37]:
# Series examples

data = pd.Series([0.1, 0.2, 0.3])
print(data)

0    0.1
1    0.2
2    0.3
dtype: float64


In [38]:
print(data.values, data.index)

[0.1 0.2 0.3] RangeIndex(start=0, stop=3, step=1)


In [39]:
print(data[1])
print(data[0:3])
print(data[2:])

0.2
0    0.1
1    0.2
2    0.3
dtype: float64
2    0.3
dtype: float64


In [40]:
# Index

val = np.arange(0, 5)
ind = val * 2
data = pd.Series(val, index=ind)
print(data)

0    0
2    1
4    2
6    3
8    4
dtype: int32


In [41]:
ind = [3, 9, 1, 10, 3]
data = pd.Series(val, index=ind)
print(data)
print(data[3])

3     0
9     1
1     2
10    3
3     4
dtype: int32
3    0
3    4
dtype: int32


In [42]:
ind = ['a', 'b', 'c', 'd', 'e']
data = pd.Series(val, index=ind)
print(data) 

a    0
b    1
c    2
d    3
e    4
dtype: int32


In [43]:
# Creating pandas Series objects

# general form: pd.Series(data, index=index)
# data can be：
# list
print("list")
print(pd.Series([1,3,8,11]))
# NumPy array
print("numpy array")
print(pd.Series(np.array([11,8,3,1])))
# scalar
print("scalar")
print(pd.Series(100))
print(pd.Series(100, index=range(3)))
# dictionary
print("dictionary")
print(pd.Series({0:1, 0.1:2, 'a':3}))

list
0     1
1     3
2     8
3    11
dtype: int64
numpy array
0    11
1     8
2     3
3     1
dtype: int32
scalar
0    100
dtype: int64
0    100
1    100
2    100
dtype: int64
dictionary
0      1
0.1    2
a      3
dtype: int64


In [44]:
# sizes must match

# pd.Series([1, 2], index=[5])   # ValueError: Length of passed values is 2, index implies 1.

#### Pandas DataFrame

In [45]:
# first DataFrame example

df = pd.DataFrame({'name': ['John Doe', 'Jane Daw', 'Jack Go'],
                   'email': ['jdoe@em.net', 'jdaw@em.net', 'jgo@em.net']})
df

name        email
0  John Doe  jdoe@em.net
1  Jane Daw  jdaw@em.net
2   Jack Go   jgo@em.net

In [46]:
# head and tail

print(df.head(4))
print(df.tail(1))

       name        email
0  John Doe  jdoe@em.net
1  Jane Daw  jdaw@em.net
2   Jack Go   jgo@em.net
      name       email
2  Jack Go  jgo@em.net


In [47]:
# More DataFrame example

years = [2000, 2001, 2002, 2003, 2004]
population = {'area_1': [1.1, 1.2, 1.5, 1.7, 2.0],
        'area_2': [0.4, 0.5, 0.7, 0.6, 0.7]}
df = pd.DataFrame(population, index = years)
df

area_1  area_2
2000     1.1     0.4
2001     1.2     0.5
2002     1.5     0.7
2003     1.7     0.6
2004     2.0     0.7

In [48]:
# DataFrame columns View

print(df.columns)

Index(['area_1', 'area_2'], dtype='object')


In [49]:
# Single-column access
print(df['area_1'])
print(df.area_2)

# Multiple-column access
print(df[['area_1', 'area_2']])

2000    1.1
2001    1.2
2002    1.5
2003    1.7
2004    2.0
Name: area_1, dtype: float64
2000    0.4
2001    0.5
2002    0.7
2003    0.6
2004    0.7
Name: area_2, dtype: float64
      area_1  area_2
2000     1.1     0.4
2001     1.2     0.5
2002     1.5     0.7
2003     1.7     0.6
2004     2.0     0.7


In [50]:
# Column addition

df['area_3'] = [1.8, 1.7, 1.5, 1.4, 1.4]
print(df)

      area_1  area_2  area_3
2000     1.1     0.4     1.8
2001     1.2     0.5     1.7
2002     1.5     0.7     1.5
2003     1.7     0.6     1.4
2004     2.0     0.7     1.4


In [51]:
# DataFrame rows View

print(df.index)

Int64Index([2000, 2001, 2002, 2003, 2004], dtype='int64')


In [52]:
# row access with iloc

print(df.iloc[0])

area_1    1.1
area_2    0.4
area_3    1.8
Name: 2000, dtype: float64


In [53]:
print(df.iloc[ [1, 3] ])

      area_1  area_2  area_3
2001     1.2     0.5     1.7
2003     1.7     0.6     1.4


In [54]:
print(df.iloc[2:5])

      area_1  area_2  area_3
2002     1.5     0.7     1.5
2003     1.7     0.6     1.4
2004     2.0     0.7     1.4


In [55]:
# row access with loc

print(df.loc[2000])

area_1    1.1
area_2    0.4
area_3    1.8
Name: 2000, dtype: float64


In [56]:
print(df.loc[ [2001, 2003]])

      area_1  area_2  area_3
2001     1.2     0.5     1.7
2003     1.7     0.6     1.4


In [57]:
print(df.loc[2002: 2004])

      area_1  area_2  area_3
2002     1.5     0.7     1.5
2003     1.7     0.6     1.4
2004     2.0     0.7     1.4


In [58]:
# Flexible Data Selection
# iloc

print(df.iloc[3, 2])

1.4


In [59]:
print(df.iloc[:3, -1])

2000    1.8
2001    1.7
2002    1.5
Name: area_3, dtype: float64


In [60]:
print(df.iloc[[0, 2], :3])

      area_1  area_2  area_3
2000     1.1     0.4     1.8
2002     1.5     0.7     1.5


In [61]:
# loc

print(df.loc[2001, 'area_2'])

0.5


In [62]:
print(df.loc[2001:2002, 'area_3'])

2001    1.7
2002    1.5
Name: area_3, dtype: float64


In [63]:
print(df.loc[[2000, 2001, 2003], :'area_2'])

      area_1  area_2
2000     1.1     0.4
2001     1.2     0.5
2003     1.7     0.6


In [64]:
# Index

print(df.columns)
print(type(df.columns))
print(df.index)
print(type(df.index))

Index(['area_1', 'area_2', 'area_3'], dtype='object')
<class 'pandas.core.indexes.base.Index'>
Int64Index([2000, 2001, 2002, 2003, 2004], dtype='int64')
<class 'pandas.core.indexes.numeric.Int64Index'>


In [65]:
# Replaceable

df.index = range(len(df)) # len(df) gives the number of rows of DataFrame
df.columns = ['a1', 'a2', 'a3']
df

a1   a2   a3
0  1.1  0.4  1.8
1  1.2  0.5  1.7
2  1.5  0.7  1.5
3  1.7  0.6  1.4
4  2.0  0.7  1.4

In [66]:
# setting a column as index

df['year'] = range(2000, 2005) # create new column year

In [67]:
df.set_index('year') # column is removed after being set as index

a1   a2   a3
year               
2000  1.1  0.4  1.8
2001  1.2  0.5  1.7
2002  1.5  0.7  1.5
2003  1.7  0.6  1.4
2004  2.0  0.7  1.4

In [68]:
df # df is unchanged without setting inplace to True

a1   a2   a3  year
0  1.1  0.4  1.8  2000
1  1.2  0.5  1.7  2001
2  1.5  0.7  1.5  2002
3  1.7  0.6  1.4  2003
4  2.0  0.7  1.4  2004

In [69]:
df.set_index('year',inplace = True)

In [70]:
df

a1   a2   a3
year               
2000  1.1  0.4  1.8
2001  1.2  0.5  1.7
2002  1.5  0.7  1.5
2003  1.7  0.6  1.4
2004  2.0  0.7  1.4

In [71]:
# Filtering

info = {'name': ['Alicia', 'Adam', 'Ashley'],
        'age': [10, 12, 9],
        'height': [155, 158, 152],
        'weight': [45, 42, 52]}

df = pd.DataFrame(info)
df.set_index('name', inplace=True)
df


age  height  weight
name                       
Alicia   10     155      45
Adam     12     158      42
Ashley    9     152      52

In [72]:
# Filter Mask

print(df['age'] >= 10)

name
Alicia     True
Adam       True
Ashley    False
Name: age, dtype: bool


In [73]:
print(df >= 10)

          age  height  weight
name                         
Alicia   True    True    True
Adam     True    True    True
Ashley  False    True    True


In [74]:
ft = (df['age'] >= 10) & (df['height'] < 158)
print(ft)

name
Alicia     True
Adam      False
Ashley    False
dtype: bool


In [75]:
# Data selection with filter mask

print(df[df['age'] >= 10])

        age  height  weight
name                       
Alicia   10     155      45
Adam     12     158      42


In [76]:
print(df.loc[df['age'] >= 10])

        age  height  weight
name                       
Alicia   10     155      45
Adam     12     158      42


In [77]:
print(df.loc[df['age'] >= 10, 'height'])

name
Alicia    155
Adam      158
Name: height, dtype: int64


In [78]:
print(df.loc[df['height'] >= 10, ['age', 'weight']])

        age  weight
name               
Alicia   10      45
Adam     12      42
Ashley    9      52


In [79]:
# Updating rows

names = {'first name': 
            ['Josh', 'John', 'Jane'],
         'last name': 
            ['Smith', 'Doe', 'Doe']}
df = pd.DataFrame(names)
df

first name last name
0       Josh     Smith
1       John       Doe
2       Jane       Doe

In [80]:
df[df['last name'] == 'Smith']['last name'] = 'Anderson'

<ipython-input-80-0a6a543d572b>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df[df['last name'] == 'Smith']['last name'] = 'Anderson'


In [81]:
df

first name last name
0       Josh     Smith
1       John       Doe
2       Jane       Doe

In [82]:
df.loc[0] = ['Jason', 'Anderson']
df

first name last name
0      Jason  Anderson
1       John       Doe
2       Jane       Doe

In [83]:
df.iloc[0] = ['Josh', 'Smith']
df

first name last name
0       Josh     Smith
1       John       Doe
2       Jane       Doe

In [84]:
df.loc[0, ['last name']] = 'Anderson'
df

first name last name
0       Josh  Anderson
1       John       Doe
2       Jane       Doe

In [85]:
df['last name'] = list(df['last name'])[::-1]
df

first name last name
0       Josh       Doe
1       John       Doe
2       Jane  Anderson

In [86]:
df['last name'] = list(df['last name'])[::-1]
df

first name last name
0       Josh  Anderson
1       John       Doe
2       Jane       Doe

In [87]:
df['last name'] = df['last name'].str.lower()
df


first name last name
0       Josh  anderson
1       John       doe
2       Jane       doe

In [88]:
# Apply, map, applymap, replace

# pd.Seires.apply()
df['last name'] = df['last name'].apply(str.title)

df

first name last name
0       Josh  Anderson
1       John       Doe
2       Jane       Doe

In [89]:
def change_Josh(fname):
    return 'Joe' if fname == 'Josh' else fname

df['first name'] = df['first name'].apply(change_Josh)

df

first name last name
0        Joe  Anderson
1       John       Doe
2       Jane       Doe

In [90]:
df['first name'] = df['first name'].apply(lambda s: 'Josh' if s == 'Joe' else s)
df

first name last name
0       Josh  Anderson
1       John       Doe
2       Jane       Doe

In [91]:
# pd.DataFrame.apply()

df.apply(len)

first name    3
last name     3
dtype: int64

In [92]:
df.apply(len, axis='index')

first name    3
last name     3
dtype: int64

In [93]:
df.apply(len, axis=1)

0    2
1    2
2    2
dtype: int64

In [94]:
df.apply(lambda ser: max(ser.apply(len)))

first name    4
last name     8
dtype: int64

In [95]:
# pandas.DataFrame.applymap()

print(df.applymap(str.upper))

  first name last name
0       JOSH  ANDERSON
1       JOHN       DOE
2       JANE       DOE


In [96]:
print(df.applymap(lambda s: s[0]))


  first name last name
0          J         A
1          J         D
2          J         D


In [97]:
# pandas.Series.map()

print(df['first name'].map({'Josh': 'Joe', 'John': 'Jay'}))

0    Joe
1    Jay
2    NaN
Name: first name, dtype: object


In [98]:
s = pd.Series({"Josh":'Joe', 'John': 'Jay'})
s

Josh    Joe
John    Jay
dtype: object

In [99]:
print(df['first name'].map(s))

0    Joe
1    Jay
2    NaN
Name: first name, dtype: object


In [100]:
# pandas.Series.replace()

print(df['first name'].replace({'Josh': 'Joe', 'John': 'Jay'}))

0     Joe
1     Jay
2    Jane
Name: first name, dtype: object


In [101]:
# Adding columns

df

first name last name
0       Josh  Anderson
1       John       Doe
2       Jane       Doe

In [102]:
df['full name'] = df['first name'] + ' ' + df['last name']
df

first name last name      full name
0       Josh  Anderson  Josh Anderson
1       John       Doe       John Doe
2       Jane       Doe       Jane Doe

In [103]:
df['year in'] = [2005, 2011, 2019]
df

first name last name      full name  year in
0       Josh  Anderson  Josh Anderson     2005
1       John       Doe       John Doe     2011
2       Jane       Doe       Jane Doe     2019

In [104]:
df['email'] = df['first name'].str.lower() +'.' \
            + df['last name'].str.lower() + \
            + df['year in'].apply(str) + '@company.com'
df

first name last name      full name  year in                          email
0       Josh  Anderson  Josh Anderson     2005  josh.anderson2005@company.com
1       John       Doe       John Doe     2011       john.doe2011@company.com
2       Jane       Doe       Jane Doe     2019       jane.doe2019@company.com

In [105]:
# assigning a Series to the new column

emp_sex = pd.Series({0: 'male', 2: 'female'})
df['gender'] = emp_sex
df

first name last name      full name  year in                          email  \
0       Josh  Anderson  Josh Anderson     2005  josh.anderson2005@company.com   
1       John       Doe       John Doe     2011       john.doe2011@company.com   
2       Jane       Doe       Jane Doe     2019       jane.doe2019@company.com   

   gender  
0    male  
1     NaN  
2  female

In [106]:
# Appending a DataFrame to Another

df2 = pd.DataFrame({'first name': ['Ron', 'Nick'],
                    'last name': ['James', 'Simons'],
                    'full name': ['Ron James', 'Nick Simons'],
                    'year in': [2010, 2011],
                    'email': ['ron.james2010@company.com', 
                              'nick.simons2011@company.com'],
                    'gender': ['male', 'male']
                   }
                  )
df2

first name last name    full name  year in                        email  \
0        Ron     James    Ron James     2010    ron.james2010@company.com   
1       Nick    Simons  Nick Simons     2011  nick.simons2011@company.com   

  gender  
0   male  
1   male

In [107]:
df.append(df2)

first name last name      full name  year in                          email  \
0       Josh  Anderson  Josh Anderson     2005  josh.anderson2005@company.com   
1       John       Doe       John Doe     2011       john.doe2011@company.com   
2       Jane       Doe       Jane Doe     2019       jane.doe2019@company.com   
0        Ron     James      Ron James     2010      ron.james2010@company.com   
1       Nick    Simons    Nick Simons     2011    nick.simons2011@company.com   

   gender  
0    male  
1     NaN  
2  female  
0    male  
1    male

In [108]:
df.append(df2, ignore_index=True)

first name last name      full name  year in                          email  \
0       Josh  Anderson  Josh Anderson     2005  josh.anderson2005@company.com   
1       John       Doe       John Doe     2011       john.doe2011@company.com   
2       Jane       Doe       Jane Doe     2019       jane.doe2019@company.com   
3        Ron     James      Ron James     2010      ron.james2010@company.com   
4       Nick    Simons    Nick Simons     2011    nick.simons2011@company.com   

   gender  
0    male  
1     NaN  
2  female  
3    male  
4    male

In [109]:
df = df.append(df2, ignore_index=True)

In [110]:
df

first name last name      full name  year in                          email  \
0       Josh  Anderson  Josh Anderson     2005  josh.anderson2005@company.com   
1       John       Doe       John Doe     2011       john.doe2011@company.com   
2       Jane       Doe       Jane Doe     2019       jane.doe2019@company.com   
3        Ron     James      Ron James     2010      ron.james2010@company.com   
4       Nick    Simons    Nick Simons     2011    nick.simons2011@company.com   

   gender  
0    male  
1     NaN  
2  female  
3    male  
4    male

In [111]:
# Removing columns or rows
# Series

df['gender'].drop([3, 4])

0      male
1       NaN
2    female
Name: gender, dtype: object

In [112]:
# DataFrame

df.drop([3, 4])

first name last name      full name  year in                          email  \
0       Josh  Anderson  Josh Anderson     2005  josh.anderson2005@company.com   
1       John       Doe       John Doe     2011       john.doe2011@company.com   
2       Jane       Doe       Jane Doe     2019       jane.doe2019@company.com   

   gender  
0    male  
1     NaN  
2  female

In [113]:
df.drop(df[df['gender'] == 'male'].index)

first name last name full name  year in                     email  gender
1       John       Doe  John Doe     2011  john.doe2011@company.com     NaN
2       Jane       Doe  Jane Doe     2019  jane.doe2019@company.com  female

In [114]:
df.drop('year in', axis = 1)

first name last name      full name                          email  gender
0       Josh  Anderson  Josh Anderson  josh.anderson2005@company.com    male
1       John       Doe       John Doe       john.doe2011@company.com     NaN
2       Jane       Doe       Jane Doe       jane.doe2019@company.com  female
3        Ron     James      Ron James      ron.james2010@company.com    male
4       Nick    Simons    Nick Simons    nick.simons2011@company.com    male

In [115]:
df.drop('year in', axis=1, inplace=True)
df

first name last name      full name                          email  gender
0       Josh  Anderson  Josh Anderson  josh.anderson2005@company.com    male
1       John       Doe       John Doe       john.doe2011@company.com     NaN
2       Jane       Doe       Jane Doe       jane.doe2019@company.com  female
3        Ron     James      Ron James      ron.james2010@company.com    male
4       Nick    Simons    Nick Simons    nick.simons2011@company.com    male

In [117]:
# Sorting Data

df.sort_values(by = 'last name')

first name last name      full name                          email  gender
0       Josh  Anderson  Josh Anderson  josh.anderson2005@company.com    male
1       John       Doe       John Doe       john.doe2011@company.com     NaN
2       Jane       Doe       Jane Doe       jane.doe2019@company.com  female
3        Ron     James      Ron James      ron.james2010@company.com    male
4       Nick    Simons    Nick Simons    nick.simons2011@company.com    male

In [118]:
df.sort_values(by=['last name', 'first name'])

first name last name      full name                          email  gender
0       Josh  Anderson  Josh Anderson  josh.anderson2005@company.com    male
2       Jane       Doe       Jane Doe       jane.doe2019@company.com  female
1       John       Doe       John Doe       john.doe2011@company.com     NaN
3        Ron     James      Ron James      ron.james2010@company.com    male
4       Nick    Simons    Nick Simons    nick.simons2011@company.com    male

In [119]:
df.sort_values(by=['last name', 'first name'], ascending=[True, False])

first name last name      full name                          email  gender
0       Josh  Anderson  Josh Anderson  josh.anderson2005@company.com    male
1       John       Doe       John Doe       john.doe2011@company.com     NaN
2       Jane       Doe       Jane Doe       jane.doe2019@company.com  female
3        Ron     James      Ron James      ron.james2010@company.com    male
4       Nick    Simons    Nick Simons    nick.simons2011@company.com    male

In [120]:
df.sort_values(by='first name', inplace=True)

In [121]:
df

first name last name      full name                          email  gender
2       Jane       Doe       Jane Doe       jane.doe2019@company.com  female
1       John       Doe       John Doe       john.doe2011@company.com     NaN
0       Josh  Anderson  Josh Anderson  josh.anderson2005@company.com    male
4       Nick    Simons    Nick Simons    nick.simons2011@company.com    male
3        Ron     James      Ron James      ron.james2010@company.com    male

In [122]:
# pandas.DataFrame.sort_index()

df.sort_index(inplace=True)
df

first name last name      full name                          email  gender
0       Josh  Anderson  Josh Anderson  josh.anderson2005@company.com    male
1       John       Doe       John Doe       john.doe2011@company.com     NaN
2       Jane       Doe       Jane Doe       jane.doe2019@company.com  female
3        Ron     James      Ron James      ron.james2010@company.com    male
4       Nick    Simons    Nick Simons    nick.simons2011@company.com    male